# Generated by Django 4.0.3 on 2022-03-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_categoty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
    ]
