# Generated by Django 4.0.3 on 2022-03-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_categoty_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
    ]
